services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: ${APP_NAME}-app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  node:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    restart: always
    container_name: ${APP_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${APP_NAME}-db
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    container_name: ${APP_NAME}-mailhog
    ports:
      - "${MAILHOG_HTTP_PORT}:8025"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    networks:
      - laravel

volumes:
  mysql-data:


networks:
  laravel:
    driver: bridge